#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Button;
                ref class TextBox;
                ref class CheckBox;
            }
        }
    }
}

namespace GAMazeSolver
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ MazeSource;
        private: ::Windows::UI::Xaml::Controls::Grid^ MazeBrowse;
        private: ::Windows::UI::Xaml::Controls::Button^ btnStep;
        private: ::Windows::UI::Xaml::Controls::Button^ btnPrev;
        private: ::Windows::UI::Xaml::Controls::Button^ btnNext;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtSolverCursor;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtEpoch;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtSteps;
        private: ::Windows::UI::Xaml::Controls::Button^ btnRun;
        private: ::Windows::UI::Xaml::Controls::Button^ btnStop;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ chkSolved;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBox;
    };
}

